# Generated by Django 6.1 on 2026-08-27 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Ma khoan')),
                ('name', models.CharField(max_length=255, verbose_name='Ten khoan ho tro')),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Don gia mac dinh')),
                ('unit_label', models.CharField(blank=True, max_length=100, verbose_name='Don vi tinh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang su dung')),
            ],
            options={
                'verbose_name': 'Loai khoan ho tro',
                'verbose_name_plural': 'Danh muc khoan ho tro',
            },
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Ma nhom')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ten nhom')),
            ],
            options={
                'verbose_name': 'Nhom don gia',
                'verbose_name_plural': 'Nhom don gia',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Ma noi bo')),
                ('name', models.CharField(max_length=255, verbose_name='Ten dich vu chuan')),
            ],
            options={
                'verbose_name': 'Loai dich vu chuan',
                'verbose_name_plural': 'Loai dich vu chuan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllowanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Nam')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Thang')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='So luong')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Don gia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Thanh tien')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_entries', to='core.employee')),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='phat.allowancetype')),
            ],
            options={
                'verbose_name': 'Khoan ho tro da nhap',
                'verbose_name_plural': 'Khoan ho tro da nhap',
                'ordering': ['-year', '-month', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_filename', models.CharField(max_length=255, verbose_name='Ten file')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Ngay du lieu (STATUS_DATE)')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='So dong')),
                ('unmatched_count', models.PositiveIntegerField(default=0, verbose_name='So dong chua anh xa duoc')),
                ('status', models.CharField(choices=[('OK', 'Thanh cong'), ('FAILED', 'Loi')], default='OK', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lan import',
                'verbose_name_plural': 'Lich su import',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Nam')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Thang')),
                ('status', models.CharField(choices=[('DRAFT', 'Tam tinh (dang cap nhat)'), ('PENDING_CONFIRMATION', 'Cho xac nhan'), ('FINALIZED', 'Da chot')], default='DRAFT', max_length=25)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ky chot luong',
                'verbose_name_plural': 'Ky chot luong',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_rate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cong theo san luong')),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tong ho tro')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tong thu nhap')),
                ('is_provisional', models.BooleanField(default=True, verbose_name='Con la tam tinh (chua xac minh)')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_pays', to='core.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pays', to='phat.monthlypayrollrun')),
            ],
            options={
                'verbose_name': 'Luong thang theo lao dong',
                'verbose_name_plural': 'Luong thang theo lao dong',
                'unique_together': {('run', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyPayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='So luong')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Don gia')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Thanh tien')),
                ('employee_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='phat.employeemonthlypay')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='phat.servicecategory')),
            ],
            options={
                'verbose_name': 'Chi tiet luong theo dich vu',
                'verbose_name_plural': 'Chi tiet luong theo dich vu',
            },
        ),
        migrations.CreateModel(
            name='ServiceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Do uu tien (nho hon = khop truoc)')),
                ('service_code', models.CharField(blank=True, max_length=10, verbose_name='SERVICE_CODE')),
                ('type_code_payroll', models.CharField(blank=True, max_length=50, verbose_name='TYPE_CODE_PAYROLL')),
                ('service_name_payroll', models.CharField(blank=True, max_length=255, verbose_name='SERVICE_NAME_PAYROLL')),
                ('area_code', models.CharField(blank=True, max_length=10, verbose_name='AREA_CODE')),
                ('weight_min_gram', models.FloatField(blank=True, null=True, verbose_name='Can nang tu (gram, bao gom)')),
                ('weight_max_gram', models.FloatField(blank=True, null=True, verbose_name='Can nang den (gram, bao gom)')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Hieu luc tu ngay')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Hieu luc den ngay')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang ap dung')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chu')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='phat.servicecategory')),
            ],
            options={
                'verbose_name': 'Quy tac anh xa dich vu',
                'verbose_name_plural': 'Bang anh xa dich vu',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostOfficeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chua xac nhan'), ('CONFIRMED', 'Da xac nhan'), ('FLAGGED', 'Bao loi')], default='PENDING', max_length=15)),
                ('comment', models.TextField(blank=True, verbose_name='Ghi chu/bao loi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='core.postoffice')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='phat.monthlypayrollrun')),
            ],
            options={
                'verbose_name': 'Xac nhan cua buu cuc',
                'verbose_name_plural': 'Xac nhan cua buu cuc',
                'unique_together': {('run', 'post_office')},
            },
        ),
        migrations.CreateModel(
            name='RouteGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=30, verbose_name='Ma tuyen (ROUTE_PO_CODE)')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Hieu luc tu ngay')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Hieu luc den ngay')),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='phat.pricegroup')),
            ],
            options={
                'verbose_name': 'Anh xa Tuyen -> Nhom gia',
                'verbose_name_plural': 'Anh xa Tuyen -> Nhom gia',
                'unique_together': {('route_code', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='RawDailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lading_code', models.CharField(max_length=50, verbose_name='LADING_CODE')),
                ('postman_code', models.CharField(blank=True, max_length=20, verbose_name='POSTMAN_CODE')),
                ('route_po_code', models.CharField(blank=True, max_length=30, verbose_name='ROUTE_PO_CODE')),
                ('post_office_code', models.CharField(blank=True, max_length=20, verbose_name='Ma buu cuc (BatchFile)')),
                ('status_code', models.CharField(blank=True, max_length=10, verbose_name='STATUS_CODE')),
                ('type_code_payroll', models.CharField(blank=True, max_length=50, verbose_name='TYPE_CODE_PAYROLL')),
                ('service_name_payroll', models.CharField(blank=True, max_length=255, verbose_name='SERVICE_NAME_PAYROLL')),
                ('area_code', models.CharField(blank=True, max_length=10, verbose_name='AREA_CODE')),
                ('service_code', models.CharField(blank=True, max_length=10, verbose_name='SERVICE_CODE')),
                ('item_type_code', models.CharField(blank=True, max_length=10, verbose_name='ITEM_TYPE_CODE')),
                ('weight_gram', models.FloatField(blank=True, null=True, verbose_name='KG (gram)')),
                ('quantity', models.FloatField(default=0, verbose_name='QUANTITY')),
                ('status_date', models.DateField(blank=True, null=True, verbose_name='STATUS_DATE')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_production_rows', to='core.employee')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='phat.importbatch')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_rows', to='phat.servicecategory')),
            ],
            options={
                'verbose_name': 'Du lieu tho hang ngay',
                'verbose_name_plural': 'Du lieu tho hang ngay',
                'indexes': [models.Index(fields=['postman_code'], name='phat_rawdai_postman_324c21_idx'), models.Index(fields=['status_date'], name='phat_rawdai_status__890bd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Don gia (dong)')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Hieu luc tu ngay')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Hieu luc den ngay')),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='phat.pricegroup')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='phat.servicecategory')),
            ],
            options={
                'verbose_name': 'Bang gia',
                'verbose_name_plural': 'Bang gia',
                'unique_together': {('service_category', 'price_group', 'effective_from')},
            },
        ),
    ]
