# Generated by Django 6.1 on 2026-08-27 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma buu cuc')),
                ('name', models.CharField(max_length=255, verbose_name='Ten buu cuc')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Khu vuc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hoat dong')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buu cuc',
                'verbose_name_plural': 'Buu cuc',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hrm_code', models.CharField(max_length=20, unique=True, verbose_name='Ma HRM')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ho va ten')),
                ('contract_type', models.CharField(blank=True, choices=[('HDLD', 'HDLD - huong Tien luong'), ('LDTK', 'LDTK - huong Thu lao')], max_length=10, verbose_name='Loai hop dong')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Chuc danh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang lam viec')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngay vao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.postoffice', verbose_name='Buu cuc')),
            ],
            options={
                'verbose_name': 'Nhan vien',
                'verbose_name_plural': 'Nhan vien',
                'ordering': ['post_office__code', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PHONG_BAN', 'Phong ban'), ('TRUONG_BUU_CUC', 'Truong buu cuc')], max_length=20, verbose_name='Vai tro')),
                ('post_office', models.ForeignKey(blank=True, help_text='Bat buoc voi vai tro Truong buu cuc, de trong voi Admin/Phong ban.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='core.postoffice', verbose_name='Buu cuc phu trach')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ho so nguoi dung',
                'verbose_name_plural': 'Ho so nguoi dung',
            },
        ),
    ]
