# Generated by Django 6.1 on 2026-08-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='postman_code',
            field=models.CharField(blank=True, db_index=True, help_text='Ma dung trong du lieu tho BatchFile/SanLuongChiTiet, khac Ma HRM.', max_length=20, verbose_name='Ma buu ta (POSTMAN_CODE)'),
        ),
    ]
