# Generated by Django 6.1 on 2026-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_postman_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma chuc danh')),
                ('name', models.CharField(max_length=255, verbose_name='Ten chuc danh')),
            ],
            options={
                'verbose_name': 'Chuc danh',
                'verbose_name_plural': 'Danh muc chuc danh',
                'ordering': ['code'],
            },
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='position_legacy',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_legacy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chuc danh (cu, xem migration)'),
        ),
    ]
