# Generated by Django 6.1 on 2026-08-28 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_positioncatalog_remove_employee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.positioncatalog', verbose_name='Chuc danh'),
        ),
    ]
