# Generated by Django 6.1 on 2026-08-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position_legacy',
        ),
    ]
