# Generated by Django 6.1 on 2026-08-28 03:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_employee_postman_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaiThacServiceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_raw', models.CharField(max_length=20, unique=True, verbose_name='Loai (theo script SQL don vi)')),
                ('nhom_dich_vu', models.CharField(blank=True, choices=[('EMS', 'EMS'), ('GHI_SO', 'Ghi so (Bao dam)'), ('BUU_KIEN', 'Buu kien'), ('PHBC', 'Phat hanh bao chi (PHBC)')], max_length=10, null=True, verbose_name='Nhom dich vu (VB1054/1182)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chu')),
            ],
            options={
                'verbose_name': 'Anh xa Loai -> Nhom dich vu Khai thac',
                'verbose_name_plural': 'Bang anh xa Khai thac',
                'ordering': ['loai_raw'],
            },
        ),
        migrations.CreateModel(
            name='KhaiThacImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_date', models.DateField(verbose_name='Ngay du lieu')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='So dong (da gop nhom)')),
                ('status', models.CharField(choices=[('OK', 'Thanh cong'), ('FAILED', 'Loi')], default='OK', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khaithac_import_batches', to='core.postoffice')),
            ],
            options={
                'verbose_name': 'Lan import Khai thac',
                'verbose_name_plural': 'Lich su import Khai thac',
                'ordering': ['-production_date'],
                'unique_together': {('post_office', 'production_date')},
            },
        ),
        migrations.CreateModel(
            name='KhaiThacPriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhom_dich_vu', models.CharField(choices=[('EMS', 'EMS'), ('GHI_SO', 'Ghi so (Bao dam)'), ('BUU_KIEN', 'Buu kien'), ('PHBC', 'Phat hanh bao chi (PHBC)')], max_length=10, verbose_name='Nhom dich vu')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Don gia (dong/cai)')),
                ('effective_from', models.DateField(verbose_name='Hieu luc tu ngay')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Hieu luc den ngay (de trong = con hieu luc)')),
                ('source_document', models.CharField(blank=True, max_length=255, verbose_name='Van ban can cu')),
            ],
            options={
                'verbose_name': 'Don gia Khai thac',
                'verbose_name_plural': 'Bang don gia Khai thac',
                'ordering': ['nhom_dich_vu', '-effective_from'],
                'unique_together': {('nhom_dich_vu', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='KhaiThacQualityCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Nam')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Thang')),
                ('he_so', models.DecimalField(choices=[(Decimal('1.1'), 'Tot (1.1)'), (Decimal('1.0'), 'Dat (1.0)'), (Decimal('0.6'), 'Chua dat (0.6)')], decimal_places=2, default=Decimal('1.0'), max_digits=3, verbose_name='He so chat luong thang')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khaithac_quality', to='core.employee')),
            ],
            options={
                'verbose_name': 'He so chat luong Khai thac thang',
                'verbose_name_plural': 'He so chat luong Khai thac thang',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='KhaiThacRawProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(verbose_name='Ngay')),
                ('ca', models.CharField(choices=[('CA1', 'Ca 1 (05:00 - 13:00)'), ('CA2', 'Ca 2 (13:00 - 21:00)'), ('CA3', 'Ca 3 (21:00 - 05:00)')], max_length=5, verbose_name='Ca')),
                ('loai_raw', models.CharField(max_length=20, verbose_name='Loai (theo script SQL don vi)')),
                ('weight_tier', models.CharField(blank=True, max_length=20, verbose_name='Muc can')),
                ('so_luong', models.PositiveIntegerField(verbose_name='So luong')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='khaithac.khaithacimportbatch')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khaithac_raw_rows', to='core.postoffice')),
            ],
            options={
                'verbose_name': 'San luong Khai thac tho (theo ca/ngay)',
                'verbose_name_plural': 'San luong Khai thac tho (theo ca/ngay)',
                'indexes': [models.Index(fields=['production_date'], name='khaithac_kh_product_52f2eb_idx'), models.Index(fields=['loai_raw'], name='khaithac_kh_loai_ra_10219a_idx')],
            },
        ),
        migrations.CreateModel(
            name='KhaiThacShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(verbose_name='Ngay lam')),
                ('ca', models.CharField(choices=[('CA1', 'Ca 1 (05:00 - 13:00)'), ('CA2', 'Ca 2 (13:00 - 21:00)'), ('CA3', 'Ca 3 (21:00 - 05:00)')], max_length=5, verbose_name='Ca')),
                ('is_truong_ca', models.BooleanField(default=False, verbose_name='Truong ca (duoc giao nhiem vu)')),
                ('actual_hours', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, verbose_name='So gio lam thuc te')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khaithac_shifts', to='core.employee')),
            ],
            options={
                'verbose_name': 'Phan ca Khai thac',
                'verbose_name_plural': 'Bang phan ca Khai thac',
                'ordering': ['-work_date', 'ca'],
                'unique_together': {('employee', 'work_date', 'ca')},
            },
        ),
    ]
