# Generated by Django 6.1 on 2026-08-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_postman_code'),
        ('khaithac', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='khaithacshiftassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='khaithacshiftassignment',
            name='cong_viec',
            field=models.CharField(default='', max_length=30, verbose_name='Cong viec (TRUONG CA/KTV/GSS...)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khaithacshiftassignment',
            name='he_so',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='He so (theo bang cham cong)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khaithacshiftassignment',
            name='raw_name',
            field=models.CharField(default='', max_length=255, verbose_name='Ten tren bang cham cong'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khaithacshiftassignment',
            name='ca',
            field=models.CharField(blank=True, choices=[('CA1', 'Ca 1 (05:00 - 13:00)'), ('CA2', 'Ca 2 (13:00 - 21:00)'), ('CA3', 'Ca 3 (21:00 - 05:00)')], max_length=5, verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='khaithacshiftassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khaithac_shifts', to='core.employee'),
        ),
        migrations.RemoveField(
            model_name='khaithacshiftassignment',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='khaithacshiftassignment',
            name='is_truong_ca',
        ),
    ]
